### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by ParkerMc01** [ORCHARD-Minecraft-Mod-Class/mod-repo-test#1]
output

[18:08:28] [main/INFO] [GradleStart]: Extra: []
[18:08:28] [main/INFO] [GradleStart]: Running with arguments:
[--userProperties, {}, --assetsDir,
C:/Users/nick_bvzmkh2/.gradle/caches/minecraft/assets, --assetIndex,
1.8, --accessToken{REDACTED}, --version, 1.8, --tweakClass,
net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass,
net.minecraftforge.gradle.tweakers.CoremodTweaker]
[18:08:28] [main/INFO] [LaunchWrapper]: Loading tweak class name
net.minecraftforge.fml.common.launcher.FMLTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Using primary tweak class name
net.minecraftforge.fml.common.launcher.FMLTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Loading tweak class name
net.minecraftforge.gradle.tweakers.CoremodTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.common.launcher.FMLTweaker
[18:08:28] [main/INFO] [FML]: Forge Mod Loader version 11.14.4.1563 for
Minecraft 1.8 loading
[18:08:28] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM,
version 1.8.0_60, running on Windows 10:amd64:10.0, installed at
C:\Program Files\Java\jre1.8.0_60
[18:08:28] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft
name- we are in a deobfuscated environment. Skipping runtime
deobfuscation
[18:08:28] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.gradle.tweakers.CoremodTweaker
[18:08:28] [main/INFO] [GradleStart]: Injecting location in coremod
net.minecraftforge.fml.relauncher.FMLCorePlugin
[18:08:28] [main/INFO] [GradleStart]: Injecting location in coremod
net.minecraftforge.classloading.FMLForgePlugin
[18:08:28] [main/INFO] [LaunchWrapper]: Loading tweak class name
net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Loading tweak class name
net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Loading tweak class name
net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:08:28] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:08:29] [main/ERROR] [FML]: The binary patch set is missing. Either
you are in a development environment, or things are not going to work!
[18:08:32] [main/ERROR] [FML]: FML appears to be missing any signature
data. This is not a good thing
[18:08:32] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:08:32] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:08:33] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[18:08:33] [main/INFO] [LaunchWrapper]: Loading tweak class name
net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:08:33] [main/INFO] [LaunchWrapper]: Calling tweak class
net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:08:33] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft
{net.minecraft.client.main.Main}
[18:08:35] [Client thread/INFO]: Setting user: Player386
[18:08:45] [Client thread/INFO]: LWJGL Version: 2.9.1
[18:08:47] [Client thread/INFO] [STDOUT]:
[net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft
Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/26/15 6:08 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A
ERROR

A detailed walkthrough of the error, its code path and all known details
is as follows:

---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_60, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 167556280 bytes (159 MB) / 297795584 bytes (284 MB) up to
928514048 bytes (885 MB)
JVM Flags: 0 total;
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML:
Loaded coremods (and transformers):
GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276'
Renderer: 'Intel(R) HD Graphics'
[18:08:48] [Client thread/INFO] [MinecraftForge]: Attempting early
MinecraftForge initialization
[18:08:48] [Client thread/INFO] [FML]: MinecraftForge v11.14.4.1563
Initialized
[18:08:48] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[18:08:49] [Client thread/INFO] [MinecraftForge]: Completed early
MinecraftForge initialization
[18:08:50] [Client thread/INFO] [FML]: Found 0 mods from the command
line. Injecting into mod discoverer
[18:08:50] [Client thread/INFO] [FML]: Searching
C:\Users\nick_bvzmkh2\git\run\mods for mods
[18:08:50] [Client thread/INFO] [test]: Mod test is missing the required
element 'name'. Substituting test
[18:09:00] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4
mods to load
[18:09:01] [Client thread/INFO] [FML]: Attempting connection with
missing mods [mcp, FML, Forge, test] at CLIENT
[18:09:01] [Client thread/INFO] [FML]: Attempting connection with
missing mods [mcp, FML, Forge, test] at SERVER
[18:09:03] [Client thread/INFO]: Reloading ResourceManager: Default,
FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft
Forge, FMLFileResourcePack:test
[18:09:03] [Client thread/INFO] [FML]: Processing ObjectHolder
annotations
[18:09:03] [Client thread/INFO] [FML]: Found 384 ObjectHolder
annotations
[18:09:03] [Client thread/INFO] [FML]: Identifying ItemStackHolder
annotations
[18:09:03] [Client thread/INFO] [FML]: Found 0 ItemStackHolder
annotations
[18:09:04] [Client thread/INFO] [FML]: Configured a dormant chunk cache
size of 0
[18:09:04] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge]
Starting version check at
http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[18:09:04] [Client thread/INFO] [FML]: Applying holder lookups
[18:09:04] [Client thread/INFO] [FML]: Holder lookups applied
[18:09:04] [Client thread/INFO] [FML]: Injecting itemstacks
[18:09:04] [Client thread/INFO] [FML]: Itemstack injection complete
[18:09:04] [Client thread/ERROR] [FML]: Fatal errors were detected
during the transition from PREINITIALIZATION to INITIALIZATION. Loading
cannot continue
[18:09:04] [Client thread/ERROR] [FML]:
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' =
Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available
'D' = Disabled 'E' = Errored
UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCH FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.4.1563.jar)
UCH Forge{11.14.4.1563} [Minecraft Forge]
(forgeSrc-1.8-11.14.4.1563.jar)
UCE test{1.0} [test] (bin)
[18:09:04] [Client thread/ERROR] [FML]: The following problems were
captured during this phase
[18:09:04] [Client thread/ERROR] [FML]: Caught exception from test
java.lang.NullPointerException
at com.test.ItemRendering.registerItemRendering(ItemRendering.java:11)
~[bin/:?]
at com.test.ItemRendering.start(ItemRendering.java:16) ~[bin/:?]
at com.test.Test.preInit(Test.java:23) ~[bin/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at
net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
~[forgeSrc-1.8-11.14.4.1563.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
~[guava-17.0.jar:?]
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
~[guava-17.0.jar:?]
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
~[guava-17.0.jar:?]
at
net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
~[forgeSrc-1.8-11.14.4.1563.jar:?]
at
net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
~[forgeSrc-1.8-11.14.4.1563.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
~[guava-17.0.jar:?]
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
~[guava-17.0.jar:?]
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
~[guava-17.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
~[guava-17.0.jar:?]
at
net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[LoadController.class:?]
at
net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
[Loader.class:?]
at
net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
[FMLClientHandler.class:?]
at net.minecraft.client.Minecraft.startGame(Minecraft.java:446)
[Minecraft.class:?]
at net.minecraft.client.Minecraft.run(Minecraft.java:356)
[Minecraft.class:?]
at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[start/:?]
at GradleStart.main(Unknown Source) [start/:?]
[18:09:04] [Client thread/INFO] [STDOUT]:
[net.minecraft.init.Bootstrap:printToSYSOUT:663]: ---- Minecraft Crash
Report ----
// Would you like a cupcake?

Time: 12/26/15 6:09 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
at com.test.ItemRendering.registerItemRendering(ItemRendering.java:11)
at com.test.ItemRendering.start(ItemRendering.java:16)
at com.test.Test.preInit(Test.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at
net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at
net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at
net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
at
net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:446)
at net.minecraft.client.Minecraft.run(Minecraft.java:356)
at net.minecraft.client.main.Main.main(Main.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
at GradleStart.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details
is as follows:

---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at com.test.ItemRendering.registerItemRendering(ItemRendering.java:11)
at com.test.ItemRendering.start(ItemRendering.java:16)
at com.test.Test.preInit(Test.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at
net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at
net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at
net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
at
net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:446)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.run(Minecraft.java:356)
at net.minecraft.client.main.Main.main(Main.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
at GradleStart.main(Unknown Source)

-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_60, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 218677680 bytes (208 MB) / 347078656 bytes (331 MB) up to
928514048 bytes (885 MB)
JVM Flags: 0 total;
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 4 mods
loaded, 4 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' =
Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available
'D' = Disabled 'E' = Errored
UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCH FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.4.1563.jar)
UCH Forge{11.14.4.1563} [Minecraft Forge]
(forgeSrc-1.8-11.14.4.1563.jar)
UCE test{1.0} [test] (bin)
Loaded coremods (and transformers):
GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276'
Renderer: 'Intel(R) HD Graphics'
Launched Version: 1.8
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276,
Intel
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate
blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
[18:09:04] [Client thread/INFO] [STDOUT]:
[net.minecraft.init.Bootstrap:printToSYSOUT:663]: #@!@# Game crashed!
Crash report saved to: #@!@#
C:\Users\nick_bvzmkh2\git\run\.\crash-reports\crash-2015-12-26_18.09.04-client.txt

**Comment by ParkerMc01** [comment]
move item rendering from preint to int
